services:
  db:
    image: postgres:16
    container_name: petroad-postgres
    environment:
      POSTGRES_DB: petroad
      POSTGRES_USER: petroad
      POSTGRES_PASSWORD: petroad
    ports: ["5433:5432"]
    volumes: [petroad-postgres:/var/lib/postgresql/data]
volumes:
  petroad-postgres:
