package com.walkmate.backend.api;
import com.walkmate.backend.domain.*; import com.walkmate.backend.repository.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/courses") @RequiredArgsConstructor public class CourseController { private final CourseRepository courses; private final UserRepository users; private final CourseLikeRepository likes;
 public record Point(double lat,double lng){} public record Create(@NotBlank String name,String coverImageUrl,@Positive double distance,Difficulty difficulty,DogSize dogSize,@DecimalMin("-90") double startLat,@DecimalMin("-180") double startLng,@Size(max=3) List<String> tags,@Size(min=2) List<Point> points){} public record Summary(Long id,String name,String coverImageUrl,double distance,Difficulty difficulty,DogSize dogSize,int likeCount,double startLat,double startLng){}
 @PostMapping public Summary create(@RequestAttribute("userId") Long userId,@Valid @RequestBody Create r){User u=users.findById(userId).orElseThrow(); Course c=new Course(u,r.name(),r.coverImageUrl(),r.distance(),r.difficulty(),r.dogSize(),r.startLat(),r.startLng()); for(int i=0;i<r.points().size();i++)c.addPoint(r.points().get(i).lat(),r.points().get(i).lng(),i); if(r.tags()!=null)r.tags().forEach(c::addTag); return to(courses.save(c));}
 @GetMapping public List<Summary> recommended(@RequestParam double lat,@RequestParam double lng){return courses.findRecommended(lat,lng).stream().map(this::to).toList();}
 @PostMapping("/{id}/like") public Summary like(@RequestAttribute("userId") Long userId,@PathVariable Long id){Course c=courses.findById(id).orElseThrow(); if(!likes.existsByUserIdAndCourseId(userId,id)){likes.save(new CourseLike(users.findById(userId).orElseThrow(),c));c.changeLikeCount(1);courses.save(c);} return to(c);}
 @DeleteMapping("/{id}/like") public Summary unlike(@RequestAttribute("userId") Long userId,@PathVariable Long id){Course c=courses.findById(id).orElseThrow(); if(likes.existsByUserIdAndCourseId(userId,id)){likes.deleteByUserIdAndCourseId(userId,id);c.changeLikeCount(-1);courses.save(c);} return to(c);}
 private Summary to(Course c){return new Summary(c.getId(),c.getName(),c.getCoverImageUrl(),c.getDistance(),c.getDifficulty(),c.getDogSize(),c.getLikeCount(),c.getStartLat(),c.getStartLng());}
}
