CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    region VARCHAR(255),
    created_at TIMESTAMP(6)
);
CREATE TABLE dog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    name VARCHAR(255), breed VARCHAR(255), profile_image VARCHAR(255),
    size VARCHAR(255) CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE')),
    birth_date DATE
);
CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(255), cover_image_url VARCHAR(255),
    distance DOUBLE PRECISION NOT NULL,
    start_lat DOUBLE PRECISION NOT NULL, start_lng DOUBLE PRECISION NOT NULL,
    difficulty VARCHAR(255) CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD')),
    dog_size VARCHAR(255) CHECK (dog_size IN ('SMALL', 'MEDIUM', 'LARGE')),
    like_count INTEGER NOT NULL
);
CREATE TABLE course_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES course(id),
    lat DOUBLE PRECISION NOT NULL, lng DOUBLE PRECISION NOT NULL,
    sequence INTEGER NOT NULL
);
CREATE TABLE course_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES course(id), tag VARCHAR(255)
);
CREATE TABLE course_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id), course_id BIGINT REFERENCES course(id),
    CONSTRAINT course_likes_user_course_unique UNIQUE(user_id, course_id)
);
CREATE TABLE walk_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id), course_id BIGINT REFERENCES course(id),
    distance DOUBLE PRECISION NOT NULL, walked_at TIMESTAMP(6)
);
CREATE INDEX walk_log_user_walked_at_idx ON walk_log(user_id, walked_at DESC);
CREATE INDEX course_point_course_sequence_idx ON course_point(course_id, sequence);
CREATE INDEX course_tag_course_idx ON course_tag(course_id);
